### ISSUE TITLE
parman doesn't find local python files when submitting to cluster

### ISSUE THREAD

**Issue by lcdumort** [reproducible-reporting/parman#12]
I am having an issue when running Jobs with parman when they are submitted to a cluster with SLURM.
The problem occurs when the run script, that is called through `submit.sh`, uses functions imported from a local python-file.
The error originates because the run script does not find the python-file. It seems as if the parent directory is, incorrectly, omitted as a python path.

To illustrate:
`workflow.py` first submits a job for `structure_initialisation`, which runs fine.
The next job, `traindata_generation`, however, depends on `xyzreporter.py`. This file is not found. I've also placed a copy of `xyzreporter.py` directly in the root directory `workflow` (i.e. at the same directory depth as `workflow.py`), but this didn't solve the issue.

```
workflow
  |- templates
  | |- structure_initialisation
  | | | - run
  | | | - submit.sh
  | |- traindata_generation
  | | | - run
  | | | - submit.sh
  | | | - xyzreporter.py
  | |- train_mlp
  | | | - run
  | | | - submit.sh
  |- workflow.py
```
This error does not occur when using a SerialRunner locally.
FYI: this does not limit my work at the moment. I am currently working around this issue by placing the code directly in the run file. It is mostly once the helper functions get larger that it will be cumbersome to keep working in a single run file.

### submit.sh
```
#!/usr/bin/env bash

module swap cluster/joltic

#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --gpus-per-task=8
#SBATCH --job-name=MLP
#SBATCH --error=job.err
#SBATCH --outpot=job.out
#SBATCH --qos=normal 
#SBATCH --time=00:30:00

parman-sbatch-wait run
```

**Comment by tovrstra** [comment]
This is due to the way Slurm and Python work. **TL;DR**: submit a `job.sh` with `sbatch` and call the Python script from `job.sh`.

Sbatch will store a copy of the script in a database. When the job is executed, it places the script in a temporary directory where it gets executed (with `$PWD` set to the path where `sbatch` was called). The Python interpreter uses the script path to construct the first item in `sys.path` and will therefore expect other modules to be present in the same temporary directory instead of the working directory (`$PWD`).
